#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

/**
 * APP NAME
 * @var string
 */
define('APP_NAME', 'console');

/**
 * 当前目录
 * @var string
 */
define('THIS_PATH', preg_replace_callback('/[\/\\\\]+/', function() { return '/'; }, __DIR__));

/**
 * 程序根目录
 * @var string
 */
define('ROOT_PATH', THIS_PATH);

// Register the Composer autoloader...
require ROOT_PATH . '/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once ROOT_PATH . '/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
