<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/Grpc/Protos/Demo.proto

namespace App\Grpc\Demo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>DataList</code>
 */
class DataList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Data items = 1;</code>
     */
    private $items;
    /**
     * Generated from protobuf field <code>.Page page = 2;</code>
     */
    protected $page = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\App\Grpc\Demo\Data>|\Google\Protobuf\Internal\RepeatedField $items
     *     @type \App\Grpc\Demo\Page $page
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\Demo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Data items = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .Data items = 1;</code>
     * @param array<\App\Grpc\Demo\Data>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \App\Grpc\Demo\Data::class);
        $this->items = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Page page = 2;</code>
     * @return \App\Grpc\Demo\Page|null
     */
    public function getPage()
    {
        return $this->page;
    }

    public function hasPage()
    {
        return isset($this->page);
    }

    public function clearPage()
    {
        unset($this->page);
    }

    /**
     * Generated from protobuf field <code>.Page page = 2;</code>
     * @param \App\Grpc\Demo\Page $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkMessage($var, \App\Grpc\Demo\Page::class);
        $this->page = $var;

        return $this;
    }

}

