<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/Grpc/Protos/Demo.proto

namespace App\Grpc\Demo;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Page</code>
 */
class Page extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 totalCount = 1;</code>
     */
    protected $totalCount = 0;
    /**
     * Generated from protobuf field <code>int64 currentPage = 2;</code>
     */
    protected $currentPage = 0;
    /**
     * Generated from protobuf field <code>int64 pageCount = 3;</code>
     */
    protected $pageCount = 0;
    /**
     * Generated from protobuf field <code>int64 perPage = 4;</code>
     */
    protected $perPage = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $totalCount
     *     @type int|string $currentPage
     *     @type int|string $pageCount
     *     @type int|string $perPage
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\Demo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 totalCount = 1;</code>
     * @return int|string
     */
    public function getTotalCount()
    {
        return $this->totalCount;
    }

    /**
     * Generated from protobuf field <code>int64 totalCount = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 currentPage = 2;</code>
     * @return int|string
     */
    public function getCurrentPage()
    {
        return $this->currentPage;
    }

    /**
     * Generated from protobuf field <code>int64 currentPage = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCurrentPage($var)
    {
        GPBUtil::checkInt64($var);
        $this->currentPage = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 pageCount = 3;</code>
     * @return int|string
     */
    public function getPageCount()
    {
        return $this->pageCount;
    }

    /**
     * Generated from protobuf field <code>int64 pageCount = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPageCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->pageCount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 perPage = 4;</code>
     * @return int|string
     */
    public function getPerPage()
    {
        return $this->perPage;
    }

    /**
     * Generated from protobuf field <code>int64 perPage = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPerPage($var)
    {
        GPBUtil::checkInt64($var);
        $this->perPage = $var;

        return $this;
    }

}

